### ISSUE TITLE
error MSB6006: "cmd.exe" exited with code 9009.

### ISSUE THREAD

**Issue by camilasan** [misch7/nextcloud-client-building#1]
Following the steps in the README to build the desktop client I always get this error running build-desktop.bat or build.bat:

```
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 9009. [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]

    65 Warning(s)
    1 Error(s)

Time Elapsed 00:03:14.76
"*** Build FAILED: desktop Release Win32 (single-build-desktop.bat)"
```

Also happens for Win64.

I did some googling but couldn't find anything helpful.  Qtkeychain and zlib build and install with no problems. 

Previously in the same machine with Visual Studio I was able to build the desktop client with no errors.

**Comment by misch7** [comment]
That's weird - oh the lovely build tool errors ^^ 🐛 

Which exact versions of Windows and Visual Studio and all the other tools are you using? ;-)

Did you upgrade VS to the latest version? Maybe it's some strange bug there.

The output of "task-build-log.bat" would also be helpful. :-)

**Comment by camilasan** [comment]
> Which exact versions of Windows and Visual Studio and all the other tools are you using? ;-)

Of course. Sorry, my bad: Windows 10, 64bit, cmake version 3.12.3, Microsoft Visual Studio Community 2017 Version 15.9.5 VisualStudio.15.Release/15.9.5+28307.280 (some extras: Microsoft Visual C++ Wizards   1.0 Microsoft Visual C++ Wizards, Visual Studio Tools for CMake   1.0,  Windows Driver Kit   10.0.17110.1002 Headers, libraries, and tools needed to develop, debug, and test Windows drivers), Git ...

And I just realized that some tools that I have are already a bit older than what you suggest in the readme, I will try to update it now.

**Comment by camilasan** [comment]
Also, before I forget: did you know Nextcloud is hiring (c++ dev) and that on the week of June 24 we have a contributor week in Stuttgart?

**Comment by camilasan** [comment]
Ok, it looks like it is building properly now. I updated Visual Studio, cmake and git. The obvious error I believe was the png2ico.exe missing from the /tools directory. 

Thanks @misch7 .

**Comment by misch7** [comment]
@camilasan Cool, that it's working and that you took the time to give it a try.
It's really exciting 😸 

You're welcome! :-)

And thanks for pointing out the c++ dev and contributor week infos, that's both very interesting. I'll drop you a mail later, if I may.

**Comment by camilasan** [comment]
> And thanks for pointing out the c++ dev and contributor week infos, that's both very interesting. I'll drop you a mail later, if I may.

Yes, you may :)
