### ISSUE TITLE
How to build OEM Client

### ISSUE THREAD

**Issue by supportreq** [misch7/nextcloud-client-building#2]
Hi,

Your script is amazing!! it just works.. I am trying to build an OEM setup with default URL etc.. how do I go about creating the OEM file? where do I place the OEM folder etc?

Please advice..

**Comment by misch7** [comment]
@supportreq Hey, thanks! Nice, it's working for you :-)

I'm not that familiar with OEM branding of the desktop client but I also did some experiments in this direction ;-)

1. First thing: For use with my build scripts you may set the environment variable `APPLICATION_VENDOR` to your preferred vendor name. This name is used by the installer and appears also under "Software" or "Apps and Features" on more recent Windows 10 systems (the place where you uninstall software).
Take a look at `defaults.inc.bat`, there you see `APPLICATION_VENDOR` is also used as the code signing key filename which you may want to tweak then in case you intend to use code signing too.
But modifying it will not change the vendor name in the client's "General" tab.

2. Advanced: Upon completion of your first build of the desktop client, take a look at these files:
`C:\Nextcloud\client-building\desktop\build\config.h`
`C:\Nextcloud\client-building\desktop\build\version.h`
If you change `APPLICATION_VENDOR` there (config.h) it will also appear in the "General" tab.

When I first released my 32-bit binary version, prior creating the build scripts, I noticed there are few variables considered by the CMake files. In fact I was only able to specify `APPLICATION_UPDATE_URL` there (as a parameter to the CMake call in `single-build-desktop.bat`: `-DAPPLICATION_UPDATE_URL=https://...`)

So I tried to modify the files above (config.h) and tweak some values like `APPLICATION_VENDOR` there and managed to apply this changes this way for future builds*.
With further tests I also managed to successfully modify other variables in "config.h" like `APPLICATION_WIZARD_HEADER_BACKGROUND_COLOR`, so just give it a try.

*And save a copy of the modified files somewhere else to avoid automatic deletion upon the next build. You should consider to add `copy` commands to `single-build-desktop.bat` after the `rm -f` (which normally would delete all the old contents of `desktop/build`).

You also might take a look at the following folders (and sub-folders), containing image resources and more theming stuff:
`desktop\theme`
`desktop\resources`

Hope, this helps. If you find out something new, please share ;-)

**Comment by supportreq** [comment]
I also looking at giving options like specifying the NextCloud URL by default, this the user cannot change.. Will check and share here.. Maybe later on you can update the scripts to include one OEM batch file :)

**Comment by misch7** [comment]
OEM branding in general is something you should address to the desktop client repo, as a feature request perhaps.

I close the issue since it‘s not related to this repo.

But yes, please feel free to share your discoveries here :)

**Comment by HimanshuSaikia** [comment]
Branding isn't difficult. Start editing from the Nextcloud.cmake file. You also need to change the icon names in themes folder with your APPLICATION_NAME found in Nextcloud.cmake. Edit the client_en.ts found in translations, theme.cpp in src/libsync, legalnotice.cpp in src/gui. Also, edit the single-build-installer-collect.bat and single-build-desktop.bat and replace nextcloud.exe and nextcloud.ico with your APPLICATION_EXECUTABLE.exe and APPLICATION_EXECUTABLE.ico
